### ISSUE TITLE
Writing to APi

### ISSUE THREAD

**Issue by ornumgiarc** [sinnerschrader/digitalfoosball#14]
Hello

I was wondering if you would share the syntax & requirements for using POST to advance scoring (say using CURL or a python script rather than the sketch) . I would like to use digital scoring without using Arduino by using a debian based client/server built into the table.

Thanks

**Comment by mviets** [comment]
+1!

**Comment by mviets** [comment]
Found out myself. :-)

 curl -X POST http://hostname:3000/events/goals/home

 curl -X POST http://hostname:3000/events/goals/visitors
